development:
  adapter: mysql2
  encoding: utf8
  database: sts_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: sts_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: sts_production
  username: root
  password: root
  host: localhost
